/** Shared browser globals for Shellie eslint fallbacks (no npm `globals` package). */
export const browserGlobals = {
  window: "readonly",
  document: "readonly",
  console: "readonly",
  navigator: "readonly",
  location: "readonly",
  localStorage: "readonly",
  sessionStorage: "readonly",
  setTimeout: "readonly",
  clearTimeout: "readonly",
  setInterval: "readonly",
  clearInterval: "readonly",
  requestAnimationFrame: "readonly",
  cancelAnimationFrame: "readonly",
  fetch: "readonly",
  URL: "readonly",
  URLSearchParams: "readonly",
  FormData: "readonly",
  Blob: "readonly",
  File: "readonly",
  FileReader: "readonly",
  Image: "readonly",
  Audio: "readonly",
  Event: "readonly",
  CustomEvent: "readonly",
  HTMLElement: "readonly",
  HTMLCanvasElement: "readonly",
  CanvasRenderingContext2D: "readonly",
  performance: "readonly",
  atob: "readonly",
  btoa: "readonly",
  structuredClone: "readonly",
  queueMicrotask: "readonly",
  matchMedia: "readonly",
  getComputedStyle: "readonly",
  alert: "readonly",
  confirm: "readonly",
  prompt: "readonly",
  devicePixelRatio: "readonly",
  innerWidth: "readonly",
  innerHeight: "readonly",
  MutationObserver: "readonly",
  ResizeObserver: "readonly",
  IntersectionObserver: "readonly",
  AbortController: "readonly",
  TextEncoder: "readonly",
  TextDecoder: "readonly",
  crypto: "readonly",
};

/** Light built-in rules — no plugins. */
export const lightRules = {
  "no-undef": "error",
  "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
  "no-redeclare": "error",
  "no-dupe-keys": "error",
  "no-unreachable": "error",
  "no-sparse-arrays": "warn",
  "valid-typeof": "error",
};
